# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: #when and where this code will run
  push:
    branches: [ "main" ] #if push to main it will run (if nothing here, runs always)
  pull_request:
    branches: [ "main" ] #if pull request to main it will run

permissions:
  contents: read

jobs: #the steps that are run
  build:

    runs-on: ubuntu-latest #defines the OS, windows-latest for example

    steps: #each dash is another step
    - uses: actions/checkout@v3 #downloads code from github
    - name: Set up Python 3.10 #install python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 #ignore for now
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
